export const testToken =
  'eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpYXQiOjE3NTE5NzYzMjgsImV4cCI6MTc1MjAwNTEyOCwiYXVkIjoiaWRwYXkucmVnaXN0ZXIud2VsZmFyZS5wYWdvcGEuaXQiLCJpc3MiOiJodHRwczovL2FwaS1pby5kZXYuY3N0YXIucGFnb3BhLml0IiwidWlkIjoiMTk1ZGE3MGYtZDNmMC00YzU3LWI2MmUtZWY0NzEzNDhlOTIwIiwibmFtZSI6IkxvcmVuem8iLCJmYW1pbHlfbmFtZSI6IkxvbGxvIiwib3JnX2VtYWlsIjpudWxsLCJvcmdfaWQiOiJiNWFlMGI0MS1iODU0LTQxNGUtODI5NS0wNzg1OTVlZTFkYjQiLCJvcmdfdmF0IjoiMDAwMDUwMDUwNTAiLCJvcmdfbmFtZSI6IlByb2R1dHRvcmUgMSIsIm9yZ19wYXJ0eV9yb2xlIjoiT1BFUkFUT1IiLCJvcmdfcm9sZSI6Im9wZXJhdG9yZSIsIm9yZ19hZGRyZXNzIjoiTGFyZ28gVmluY2Vuem8gVmVsYSAxLCAyMDg2MiBBUkNPUkUgKE1CKSIsIm9yZ19wZWMiOiJjb211bmUuYXJjb3JlQHBlYy5yZWdpb25lLmxvbWJhcmRpYS5pdCJ9.G7hWYvUXqlnHC-ALZi5Q9sgO2EFgSD03cAAHlQ_Q0em2Ntnkucb6VLk_dyV3tEXLvPSClRR4Eh0mUs5P3u7EFtDqpjDRVYLpDrmZ0DdcV_eDdaSsZZs_bfilYW7LZH373QJNaeDog6JeQ-yHFgQIdshxHHRNHk21VC2M8nh3d0tQg_Ptv5HhZ9BKgCVzN4MvZtaimekWUx-aVh-tDBvzu78L4S5qlGoj3dts-rLRjLkarpYT1-l_LMMRmq6lZ79pCWNwVxSTNsq0V7EkgO0VmuttDPTCMlui6RBfuojDQBCs2rYpRPuEE86Ze90OIGKhkQKcHhk3_XD35zv9j4in2g';

const IS_DEVELOP = process.env.NODE_ENV === 'development';
export const MOCK_USER = IS_DEVELOP;
export const LOG_REDUX_ACTIONS = IS_DEVELOP;

export const LOADING_TASK_LOGIN_CHECK = 'LOGIN_CHECK';
export const LOADING_TASK_SEARCH_PARTIES = 'SEARCH_PARTIES';
export const LOADING_TASK_SEARCH_PARTY = 'SEARCH_PARTY';
export const LOADING_TASK_SEARCH_PRODUCTS = 'SEARCH_PRODUCTS';

export enum PRODUCTS_CATEGORY {
  WASHINGMACHINES = 'WASHINGMACHINES',
  WASHERDRIERS = 'WASHERDRIERS',
  OVENS = 'OVENS',
  RANGEHOODS = 'RANGEHOODS',
  DISHWASHERS = 'DISHWASHERS',
  TUMBLEDRYERS = 'TUMBLEDRYERS',
  REFRIGERATINGAPPL = 'REFRIGERATINGAPPL',
  COOKINGHOBS = 'COOKINGHOBS',
}

export const displayRows = 8;
export const emptyData = '-';
