export const testToken =
  'eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpYXQiOjE3NTMzNjcyNzAsImV4cCI6MTc1MzM5NjA3MCwiYXVkIjoiaWRwYXkucmVnaXN0ZXIud2VsZmFyZS5wYWdvcGEuaXQiLCJpc3MiOiJodHRwczovL2FwaS1pby5kZXYuY3N0YXIucGFnb3BhLml0IiwidWlkIjoiMTk1ZGE3MGYtZDNmMC00YzU3LWI2MmUtZWY0NzEzNDhlOTIwIiwibmFtZSI6IkxvcmVuem8iLCJmYW1pbHlfbmFtZSI6IkxvbGxvIiwib3JnX2VtYWlsIjpudWxsLCJvcmdfaWQiOiJiNWFlMGI0MS1iODU0LTQxNGUtODI5NS0wNzg1OTVlZTFkYTEiLCJvcmdfdmF0IjoiODcwMDMyOTAxNTkiLCJvcmdfZmMiOiIwNTY3ODcyMTAwMSIsIm9yZ19uYW1lIjoiQWcuTmF6LkF0dHJhemlvbmUgSW52ZXN0aW1lbnRpIFN2aWx1cHBvIEltcHJlc2EgU3BhIiwib3JnX3BhcnR5X3JvbGUiOiJPUEVSQVRPUiIsIm9yZ19yb2xlIjoiaW52aXRhbGlhIiwib3JnX2FkZHJlc3MiOiJWaWEgQ2FsYWJyaWEsIDQ2IC0gMDAxODcgUm9tYSAoUk0pLCAyMDg2MiBST01BIChSTSkiLCJvcmdfcGVjIjoiaW52aXRhbGlhQHBlYy5pbnZpdGFsaWEuaXQgICJ9.fWbvltTEqYL9lgrQvl3sJBku1o4ECngylDBgim7c543WEXMCTkmJewlOQGx9PjFukh6tLJhsQZCJsYYQ7JJn9j2eJQKv9D2kHthNyZXfdFFZuPENY5sayqnn9duWwupM-FMNAxGC_jkgpLvgoZtcPikcipNgQ4muQ1qp5nBqiFYlRPRFNaZiPu4nRR9G9pn9afTtPOV6JP3lpNVZMf60fX8ynNPEBsda8YUl2s9DBpRwX3GjAg9rH13kDR-D7-d1SaJJT18dxQ-S27ROVtfDxeb-B4ATsdx6btmYptrLjiWwa9PXaWqIO1JxXCDLUiQ2m68Zy25JAbAZIkKm36dRbw';

const IS_DEVELOP = process.env.NODE_ENV === 'development';
export const MOCK_USER = IS_DEVELOP;
export const LOG_REDUX_ACTIONS = IS_DEVELOP;

export const LOADING_TASK_LOGIN_CHECK = 'LOGIN_CHECK';
export const LOADING_TASK_SEARCH_PARTIES = 'SEARCH_PARTIES';
export const LOADING_TASK_SEARCH_PARTY = 'SEARCH_PARTY';
export const LOADING_TASK_SEARCH_PRODUCTS = 'SEARCH_PRODUCTS';

export enum PRODUCTS_CATEGORY {
  WASHINGMACHINES = 'WASHINGMACHINES',
  WASHERDRIERS = 'WASHERDRIERS',
  OVENS = 'OVENS',
  RANGEHOODS = 'RANGEHOODS',
  DISHWASHERS = 'DISHWASHERS',
  TUMBLEDRYERS = 'TUMBLEDRYERS',
  REFRIGERATINGAPPL = 'REFRIGERATINGAPPL',
  COOKINGHOBS = 'COOKINGHOBS',
}

export enum PRODUCTS_STATES {
  APPROVED = 'Approvato',
  EXCLUDED = 'Escluso',
  MARKED = 'Contrassegnato',
}

export const INVITALIA = 'invitalia';

export const PAGINATION_ROWS_PRODUCTS = 20;
export const PAGINATION_ROWS_UPLOADS = 20;
export const EMPTY_DATA = '-';
export const MAX_TABLE_HEIGHT = 500;

export const maxLengthEmail: number = 40;
export const maxLengthOverviewProd: number = 75;
export const maxLengthOverviewInvit: number = 140;
