name: 'coverage'

on:
  pull_request:
    branches:
      - release-dev
      - release-uat
      - main

jobs:
  sonarcloud:
    runs-on: ubuntu-latest

    steps:
      # Checkout repository
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Install dependencies
      - name: Install dependencies
        run: |
          corepack enable
          yarn install --immutable --check-cache || yarn install --force
          yarn global add @craco/craco

      # Optional: fix peer dependency issue
      - name: Force install dependencies (ignore peer conflicts)
        run: |
          npm install --legacy-peer-deps

      # Run Jest with coverage
      - name: Jest Coverage Report
        uses: ArtiomTr/jest-coverage-report-action@v2.0-rc.6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          test-script: yarn test:coverage
          threshold: 90
          annotations: none

      # SonarCloud scan
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v5.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.organization=${{ vars.SONARCLOUD_ORG }}
            -Dsonar.projectKey=${{ vars.SONARCLOUD_PROJECT_KEY }}
            -Dsonar.projectName="${{ vars.SONARCLOUD_PROJECT_NAME }}"
