name: 'coverage'

on:
  pull_request:
    branches:
      - release-dev
      - release-uat
      - main

jobs:
  sonarcloud:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Install dependencies
      - name: Install dependencies
        run: |
          corepack enable
          yarn install --immutable --check-cache || yarn install --force

      - name: Generate api client
        run: yarn generate

      - name: Run tests with coverage
        run: yarn test:coverage

      # Upload Jest Coverage Report
      - name: Jest Coverage Report
        uses: ArtiomTr/jest-coverage-report-action@v2.0-rc.6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          test-script: yarn test:coverage
          threshold: 90
          annotations: none
          package-manager: yarn
          coverage-file: ./coverage/lcov.info
          base-coverage-file: ./coverage/lcov.info

      # SonarCloud scan
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v5.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.organization=${{ vars.SONARCLOUD_ORG }}
            -Dsonar.projectKey=${{ vars.SONARCLOUD_PROJECT_KEY }}
            -Dsonar.projectName="${{ vars.SONARCLOUD_PROJECT_NAME }}"
