name: 'coverage'

on:
  pull_request:
    branches:
      - release-dev
      - release-uat
      - main

jobs:
  sonarcloud:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install dependencies
        run: |
          corepack enable
          yarn install --immutable --check-cache || yarn install --force

      - name: Generate api client
        run: yarn generate

      - name: Run tests with coverage
        run: yarn test:coverage

      - name: Debug coverage file
        run: |
          echo "Contenuto iniziale del file lcov:"
          head -n 20 ./coverage/lcov.info || echo "File non trovato"

      - name: Coverage Report
        uses: romeovs/lcov-reporter-action@v0.3.1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          lcov-file: ./coverage/lcov.info
          delete-old-comments: true

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v5.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.organization=${{ vars.SONARCLOUD_ORG }}
            -Dsonar.projectKey=${{ vars.SONARCLOUD_PROJECT_KEY }}
            -Dsonar.projectName="${{ vars.SONARCLOUD_PROJECT_NAME }}"
            -Dsonar.javascript.lcov.reportPaths=coverage/lcov.info
            -Dsonar.projectBaseDir=.
            -Dsonar.javascript.file.suffixes=.js,.jsx
            -Dsonar.typescript.file.suffixes=.ts,.tsx
            -Dsonar.sources=.
            -Dsonar.tests=**/__tests__
            -Dsonar.test.inclusions=**/__tests__/**/*.test.tsx
            -Dsonar.testExecutionReportPaths=test-report.xml
            -Dsonar.sourceEncoding=UTF-8
            -Dsonar.verbose=true
            -Dsonar.javascript.lcov.reportPaths=coverage/lcov.info
            -Dsonar.typescript.tsconfigPath=tsconfig.json
